giantswarm/standup

cmd/cleanup/command.go, cmd/cleanup/error.go, cmd/cleanup/flag.go, cmd/cleanup/runner.go, cmd/command.go, cmd/create/command.go, cmd/create/error.go, cmd/create/flag.go, cmd/create/runner.go, cmd/test/runner.go, pkg/gsclient/error.go, pkg/gsclient/gsclient.go
Breaks `standup create` and `standup cleanup` into separate commands
This relies on the cluster existing to know which release to delete. If cluster doesn't exist, it could leak the release. Let's talk about how to fix that separately, either by passing the release name as an argument or by naming them predictably
=> Separate create and cleanup commands

cmd/cleanup/runner.go, cmd/create/flag.go, cmd/create/runner.go, cmd/test/flag.go, cmd/test/runner.go, cmd/test/runner_test.go, go.mod, go.sum, pkg/gsclient/gsclient.go
I checked how tekton clones the current git repo and made sure that the command I chose was compatible. It's basically:
- `git fetch`
- `git diff --name-status origin/master`
which gives us:
```
A       aws/v13.0.0/README.md
A       aws/v13.0.0/kustomization.yaml
A       aws/v13.0.0/release.diff
A       aws/v13.0.0/release.yaml
```
which can be parsed to determine that we're testing release 13.0.0 for AWS.
The code is still rough, I can clean it up before merging if you prefer, but wanted to get this code out so you're not blocked tomorrow.
=> Implement git diff, logs, and backoff

Dockerfile
Building on `golang` and running on `alpine` has issues (I think related to architecture or dependencies) and I didn't want to go down a rabbit hole getting the build perfect for this temporary branch. 
As a result, the base for `standup` is `golang` until the `gsctl` changes are merged and built properly, but the intent is to revert this
=> Clone and build gsctl branch for use by standup

cmd/create/flag.go, cmd/create/runner.go
Kubeconfig will be stored at the path given by `--output`. If no value is given, the default location `/workspace/cluster/kubeconfig` will be used.
Towards https://github.com/giantswarm/giantswarm/issues/12553
=> Write kubeconfig to path provided by --output flag

CHANGELOG.md, pkg/gsclient/gsclient.go
Handles the case where `gsctl create cluster --output json` fails with an error `error` rather than `created-with-errors` which leads to an empty cluster ID and the following error in Tekton create-cluster step:
```
No cluster name or ID specified.
Please specify a cluster name or ID. Use --help for details.
```
Also removed some unused stderr handling since `--output json` seems to return errors to stdout.
=> Improve error handling

pkg/gsclient/gsclient.go
We're currently getting a lot of warnings when trying to create a cluster and there is no way to suppress them
=> Ignore non-json output when calling to gsctl

pkg/gsclient/gsclient.go
So the JSON could also be an array and start with [. This is hacky and will break if there are brackets in the pre-json output so I'm open for ideas. 
I tried ignoring the warnings only, but it turns out that gscliauth talks a lot more than that. We could also change stdout in gsctl temporarily, but it doesn't sound less hacky. This is a temporarily solution until we find a better way to do it.
=> Skip non-json output

CHANGELOG.md, Dockerfile
This PR changes the Dockerfile to use the binary release of gsctl.
=> Remove gsctl build step

CHANGELOG.md, cmd/create/runner.go, pkg/gsclient/gsclient.go
This PR changes the usage of `gsctl create kubeconfig` to let `gsctl` write the kubeconfig file directly to the specified path.
=> use --self-contained of gsctl for creating kubeconfig

cmd/cleanup/flag.go
Privider flag was a copy/paste of the kubeconfig one so there are two flags defined as -k
=> Fix provider flag

cmd/create/runner.go, pkg/git/git.go
If someone deletes a file (for example archiving a release) in master then the current version of diff will show the archived files as new and we will end up choosing the wrong release to deploy. By getting the diff from the merge base, we guarantee that we only get the new files from our PR.
=> Diff against the merge base

CHANGELOG.md, cmd/create/release/runner.go, cmd/create/release/runner_test.go, go.mod
When testing alpha / beta releases, the generated release name requires
special handling in order to comply with release name validation rules.
=> Refine test release name generation for test releases

CHANGELOG.md, cmd/wait/flag.go, cmd/wait/runner.go
This adds a wait for `external-dns` on our two cloud providers. Please check and voice opinions if you think this makes sense.
=> Wait for external-dns in wait task

cmd/create/cluster/runner.go, pkg/gsclient/client.go, pkg/gsclient/cluster.go, pkg/gsclient/types.go, pkg/key/key.go
Towards https://github.com/giantswarm/giantswarm/issues/13569
Removes/centralizes duplicate gsctl command line calls, and cleans up a couple TODO comments we no longer need.
The idea is just to reduce how many places we have duplicated flag values and add a little more structure on top of the raw gsctl calls.
=> Tidy up some TODOs

CHANGELOG.md, Dockerfile
I need to use `jq` from our tekton pipelines before calling `standup` , so it would be convenient if the Docker image would already contain `jq`.
=> Install jq in the Docker image

CHANGELOG.md, cmd/create/cluster/error.go, cmd/create/cluster/flag.go, cmd/create/cluster/runner.go, go.mod, go.sum, pkg/gsclient/cluster.go
We were being throttled by Azure due to the high number of clusters being created on our subscription. Using different organizations for the created clusters can help in this regard, because different organizations may use different subscriptions.
Also, by selecting different organizations we can test the BYOC scenario, with organizations using different subscriptions than the management cluster.
For the implementation, I listed the `Organization` objects in the management cluster labeled in a certain way. If we want an organization to be used for conformance testing, we just need to add that label to it and it'd be picked up.
=> Select random organization when creating cluster

CHANGELOG.md, cmd/create/testoperatorrelease/runner.go
When creating a new release to test an operator we need to use a newer version than latest or we won't be able to upgrade to it, because admission controller prevents upgrading. To avoid the following error
```
Error from server (BadRequest): admission webhook "validate.cluster.update.azure-admission-controller-unique.giantswarm.io" denied the request: downgrading is not allowed error: downgrading is not allowed (attempted to downgrade from 14.1.0 to 14.1.0-1613059489)
```
our created release should've been `14.1.1-1613059489`.
=> Use latest release next patch when creating release

CHANGELOG.md, cmd/cleanup/runner.go
Toward: https://github.com/giantswarm/giantswarm/issues/13971
> My idea is to update codes here to check whether cluster namespace has been deleted, rather than check the kubeconfig secret or app CRs deletion individually.
=> Check the cluster namespace deletion from cleanup

CHANGELOG.md, cmd/cleanup/runner.go, cmd/create/release/runner.go, pkg/key/key.go
First steps towards making the test infra work with CAPI clusters.
This PR avoids creating (and deleting) a temporary test release in case the release being tested is a CAPI one.
=> Avoid creating and deleting a test release for CAPI releases.

CHANGELOG.md, cmd/wait/flag.go, cmd/wait/runner.go
This allows for more reliable tests
=> Add flag to specify the expected number of nodes to be ready in `wait ready` command.

CHANGELOG.md, cmd/wait/runner.go
Capi clusters and GS clusters use a different set of labels for the coredns service.
This PR allows detecting the fact coredns is running correctly for both label sets.
=> Add support to CAPI clusters in the `wait ready` command.
